import Foundation
import Testing
import Domain
import Learning
@testable import Audio

struct LegatoChainPracticeTests {
    private func run(rate: Double, mode: String = "correct", midi: Int = 60, plateauSeconds: Double = 0.4, cycles: Int = 1) throws -> AssessedPractice {
        let plateauTicks = Int64((plateauSeconds * 960).rounded())
        let offsets = [0] + (0..<cycles).flatMap { _ in [3, 7, 3, 0] }
        let chain = try LegatoChain(targets: (1..<offsets.count).map { index in
            let delta = offsets[index] - offsets[index - 1]
            return try .init(kind: delta < 0 ? .pullOff : delta == 4 ? .tap : .hammerOn, semitones: delta, startTick: Int64(index) * plateauTicks)
        })
        let durationTicks = plateauTicks * Int64(offsets.count), durationSeconds = plateauSeconds * Double(offsets.count)
        let position = try #require(TuningProfile.standard.strings.compactMap { string -> FretPosition? in
            let fret = midi - string.openPitch.midi
            guard (0...17).contains(fret) else { return nil }
            return try? FretPosition(string: string.number, fret: fret)
        }.first)
        let event = try MusicalEvent(id: "chain", startTick: 0, durationTicks: durationTicks, kind: .note, positions: [position], legatoChain: chain)
        let rest = try MusicalEvent(id: "rest", startTick: durationTicks, durationTicks: 1920, kind: .rest)
        let endpoint = try CalibrationEndpoint(uid: "motion-generated", channel: 1, sampleRate: rate, bufferFrames: 512, deviceLatencyFrames: 0, streamLatencyFrames: 0)
        let route = try CalibrationRoute(input: endpoint, output: endpoint, backendVersion: MonophonicAnalyzer.algorithmVersion)
        let calibration = try CalibrationProfile(route: route, method: .measured, residualOffsetSeconds: 0, uncertaintySeconds: 0.015,
            evidence: CalibrationEvidence(algorithmVersion: "generated", matchedPulses: 12, missedPulses: 0, extraPulses: 0,
                durationSeconds: 25, residualP95Seconds: 0.005, driftSeconds: 0))
        let config = try PracticeConfiguration(exercise: Exercise(id: "motion-test", events: [event, rest]), instrument: InstrumentProfile(), bpm: 60, route: route, calibration: calibration)
        let analyzer = try MonophonicAnalyzer(sampleRate: rate)
        var collector = PracticeEvidenceCollector(configuration: config, baseline: analyzer.snapshot())
        let start = 0.2 + config.countInSeconds, frequency = try Pitch(midi: midi).frequency()
        var pcm: [Float] = [], phase = 0.0, random: UInt64 = 17
        for index in 0..<Int((start + durationSeconds + 2.5) * rate) {
            let time = Double(index) / rate - start
            if time < 0 || time >= durationSeconds { pcm.append(0); continue }
            // Independent phase-accumulated PCM, never generated by TransportPlan or LegatoChain.
            let phaseIndex = min(offsets.count - 1, Int(time / plateauSeconds))
            var cents = Double(offsets[phaseIndex] * 100)
            if mode == "stuck" { cents = 0 }
            if mode == "skipped" && offsets[phaseIndex] == 3 { cents = 700 }
            if mode == "wrong-direction" { cents = -cents }
            phase += 2 * .pi * frequency * pow(2, cents / 1200) / rate
            random = random &* 6364136223846793005 &+ 1
            let envelope = min(1, time / 0.005, (durationSeconds - time) / 0.005)
            let signal = 0.15 * (sin(phase) + 0.3 * sin(2 * phase) + 0.15 * sin(3 * phase)) * envelope
            let sample: Float
            switch mode {
            case "silence": sample = 0
            case "missing-middle" where phaseIndex == 2: sample = 0
            case "noise": sample = Float((Double(random >> 32) / Double(UInt32.max) * 2 - 1) * 0.2)
            case "clipped": sample = Float(signal * 12)
            default: sample = Float(signal)
            }
            pcm.append(sample)
        }
        for frame in stride(from: 0, to: pcm.count, by: 769) {
            pcm.withUnsafeBufferPointer { ptr in analyzer.process(.init(rebasing: ptr[frame..<min(frame + 769, ptr.count)]), startHostSeconds: 100 + Double(frame) / rate) }
            try collector.consume(analyzer.snapshot(), renderEpochSeconds: 100.2)
        }
        let evidence = try PracticeEvidence(id: UUID(), configuration: config, startedAt: Date(timeIntervalSince1970: 1), finishedAt: Date(timeIntervalSince1970: 12),
            phase: .completed, reason: nil, signalConfirmed: true, renderEpochSeconds: 100.2, maximumClockDriftSeconds: 0,
            attacks: collector.attacks, clipping: collector.clipping, uncertainSignal: collector.uncertainSignal,
            pitchContour: collector.pitchContourTrace(), analysisVersion: collector.analysisVersion)
        return try AssessmentEngine.evaluate(evidence)
    }
    @Test(arguments: [44100.0, 48000.0]) func slowChainsTrackEveryTargetAtPitchAndPlateauBounds(rate: Double) throws {
        for (midi, seconds, cycles) in [(55, 0.4, 1), (60, 0.4, 2), (76, 0.4, 1), (60, 1.0, 1)] {
            let result = try run(rate: rate, midi: midi, plateauSeconds: seconds, cycles: cycles)
            #expect(result.validity == .valid && (result.legatoChainScore ?? -1) > 95, "\(midi), \(seconds), \(rate): \(String(describing: result.legatoChains))")
            #expect(result.matchedCount == 1 && result.scoredExtras.isEmpty)
            #expect(result.parameters == .withLegatoChains)
            #expect(result.legatoChains?.notes.first?.phases.count == cycles * 4 + 1)
            #expect(try JSONDecoder().decode(AssessedPractice.self, from: JSONEncoder().encode(result)) == result)
        }
    }
    @Test func wrongSilentClippedAndUnknownInputRemainDifferent() throws {
        for mode in ["stuck", "skipped", "wrong-direction", "silence", "missing-middle", "noise", "clipped"] {
            let result = try run(rate: 48000, mode: mode)
            if mode == "noise" || mode == "clipped" {
                #expect(result.validity == .insufficientSignal && result.legatoChainScore == nil, "\(mode): \(String(describing: result.legatoChains))")
            } else {
                #expect(result.validity == .valid && (result.legatoChainScore ?? 100) < 90, "\(mode): \(String(describing: result.legatoChains))")
                if mode == "silence" { #expect(result.legatoChainScore == 0 && result.matchedCount == 0) }
            }
        }
    }
}
